name: AvatarSelection
main: net.bendercraft.spigot.avatar.selection.AvatarSelectionPlugin
author: [Koudja, Noko]
description: Plugin to automatize the avatar selection
depend: [Bending]
version: 1.5.0
api-version: 1.13
load: POSTWORLD
commands:
   avatar:
      description: Avatar commands.