name: AvatarSelection
main: AvatarSelectionPlugin
author: [Koudja, Noko]
description: Plugin to automatize the avatar selection
version: 1.0.0
load: POSTWORLD
commands:
   avatar:
      description: Avatar commands.